### ISSUE TITLE
postProcessScript.sh Is blank

### ISSUE THREAD

**Issue by macbentosh** [boatmeme/plex-comskip#1]
Steps say to download postProcessScript.sh

File is zero kb and blank

**Comment by clockworked247** [comment]
+1  postProcessScript.sh is definitely blank.

**Comment by NoahJaehnert** [comment]
+1 as well... postProcessScript.sh is blank 👎  :(

**Comment by boatmeme** [comment]
Thanks for the email @clockworked247. FWIW, I did catch the notification for this issue and added it to my mental collection of spinning plates.

I ran into an issue where I was running out of temp space in the docker container and had not yet figured out the best way to generalize the solution - mapping a volume for the comskip ```temp-work``` directory - for the purposes of this project. 

I will eventually get back to this, but in the meantime, have a look at my own setup and adjust where necessary.

### postProcessScript.sh
```
#!/bin/bash
LogFile=/tmp/postProcess.log
DOCKER=/share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker

exec 3>&1 1>>${LogFile} 2>&1

${DOCKER} run --rm -v "/share/Public/plex-comskip/temp:/processing-temp" -v "/share/Public/plex-comskip/PlexComskip.conf:/opt/PlexComskip/PlexComskip.conf" -v "$1:/data$1" boatmeme/plex-comskip:latest /opt/PlexComskip/PlexComskip.py "/data$1"
```
### PlexComskip.conf
```[Helper Apps]

# Path to the comskip binary.
comskip-path: /opt/Comskip/comskip

# Path to the comskip INI file. Defaults to the same directory as the PlexComskip script.
# comskip-ini-path: ~/comskip.ini

# Path to the ffmpeg binary.
ffmpeg-path: /usr/bin/ffmpeg

# Nice level. Used for file copies, comskip analysis, and ffmpeg processing. 0 (default, full priority) - 20 (most nice)
nice-level: 0

[Logging]

# Log file location.
logfile-path: /var/log/PlexComskip.log

# Split the log output to the console? Useful for debugging.
console-logging: True

[File Manipulation]

# Specify a temp directory for interstitial files. This should be local, fast, and have enough free space for ~2x your largest video. Defaults to system temp location.
temp-root: /processing-temp

# Should we copy the original file to the temp directory? Useful if disk access to the original is slower than your temp location. Defaults to False.
copy-original: False

# Always save the intermediate files? Useful for debugging. Defaults to False.
save-always: False

# Save intermediate files when something goes wrong? Also useful for debugging and less space intensive. Defaults to True.
save-forensics: False
```

**Comment by macbentosh** [comment]
added the post sh to the dvr on plex.  Is that all after i pull the docker image?
Just starting out with docker...Can someone put some dummy proof steps for the qnap?

**Comment by macbentosh** [comment]
Changed the postscript for my setup.  Here is the error from running 
[/share/Container/comskip] # tail -f -n 5 /tmp/postProcess.log  
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /opt/PlexComskip/PlexComskip.conf, line: 2
'comskip-path: /opt/Comskip/comskip\n'
Traceback (most recent call last):
  File "/opt/PlexComskip/PlexComskip.py", line 21, in <module>
    config.read(config_file_path)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /opt/PlexComskip/PlexComskip.conf, line: 2
'comskip-path: /opt/Comskip/comskip\n'

**Comment by boatmeme** [comment]
@macbentosh looks like maybe it can't read the PlexComskip.conf. I'm wondering if you copy-pasted from upthread and it picked up some bad whitespace?

Try just editing the PlexComskip.conf from the repository, and manually editing this line:

```
# Specify a temp directory for interstitial files. This should be local, fast, and have enough free space for ~2x your largest video. Defaults to system temp location.
temp-root: /processing-temp
```

That's the only difference between the version I posted in here and the one committed to the repo.

**Comment by dinki** [comment]
> @macbentosh looks like maybe it can't read the PlexComskip.conf. I'm wondering if you copy-pasted from upthread and it picked up some bad whitespace?
> 
> Try just editing the PlexComskip.conf from the repository, and manually editing this line:
> 
> ```
> # Specify a temp directory for interstitial files. This should be local, fast, and have enough free space for ~2x your largest video. Defaults to system temp location.
> temp-root: /processing-temp
> ```
> That's the only difference between the version I posted in here and the one committed to the repo.

Confirming that I had this issue also.  I downloaded from the repo and made the change to temp-root and it appears to be working now.  Thanks for the container.  Exactly what I was looking for!

**Comment by nebhead** [comment]
For what it's worth, it worked for me too after downloading from this repo and making the one line edit (not the @rogue-bryan version).  After reviewing the log, it seems I am still getting errors, but the script runs and completes the job.  

Also, side note, would be nice if we had an option to write the modified file to another location.
